### ISSUE TITLE
Обновить названия эксепшнов в соответствии с документацией API v4

### ISSUE THREAD

**Issue by inner-whisper** [sputnik8/atol-rb#17]
При тестировании интеграции с АТОЛ с помощью данного gem-а заметил следующую особенность:
- При попытке запросить документ с просроченным токеном мне возвращается эксепшн `Atol::StateBadRequestError ({"error":{"code":11,"error_id":"adec8ba2-6ec3-4163-bf1f-f0a663a9da56","text":"Переданный токен не активен","type":"system"},"timestamp":"24.04.2020 13:23:55"})`
- При попытке запросить документ с неправильным токеном мне возвращается эксепшн `Atol::IncomingExistExternalIdError ({"error":{"code":10,"error_id":"4bd55993-f094-4ea9-ae06-60dcf3bacfc7","text":"Не распознан токен запроса","type":"system"},"timestamp":"24.04.2020 13:24:48"})`

Если посмотреть в документацию https://online.atol.ru/files/API_atol_online_v4.pdf в таблицу 6 на странице 60, то можно увидеть, что передаваемым кодам ошибок (поле `code` в json с ошибкой) есть соответствующие человекопонятные названия:
Ошибка | Код ошибки
------------ | -------------
MissingToken | 10
ExpiredToken | 11

Мне данные названия кажутся более понятными и соответствующими сути происходящих ошибок.

Предлагаю названия всех эксепшнов в https://github.com/sputnik8/atol-rb/blob/5ef433f7fc7a19d19749f07ef4cd525a3dfb8995/lib/atol/errors.rb#L31-L51 заменить на сформированные от названий в документации (название ошибки в документации + добавление `Error` в конце названия эксепшна).

Т.е. для моего примера это было бы в следующем виде:
- При попытке запросить документ с просроченным токеном мне бы вернулся эксепшн `Atol::ExpiredTokenError ({"error":{"code":11,"error_id":"adec8ba2-6ec3-4163-bf1f-f0a663a9da56","text":"Переданный токен не активен","type":"system"},"timestamp":"24.04.2020 13:23:55"})`
- При попытке запросить документ с неправильным токеном мне бы вернулся эксепшн `Atol::MissingTokenError ({"error":{"code":10,"error_id":"4bd55993-f094-4ea9-ae06-60dcf3bacfc7","text":"Не распознан токен запроса","type":"system"},"timestamp":"24.04.2020 13:24:48"})`

**Comment by inner-whisper** [comment]
@GeorgeGorbanev есть ли сейчас существенные проблемы с данными изменениями? Я мог бы сделать PR по данной проблеме, но хотел сначала обсудить 😃

**Comment by GeorgeGorbanev** [comment]
Привет! Да, похоже мое упущение. При переходе с v3 на v4 они поменяли коды ошибок, а я не увидел. Полагаю, теперь `10 => IncomingExistExternalIdError` нужно превратить в `33 => IncomingExternalIdAlreadyExists`, но это довольно важный эксепшн и нельзя ломать обратную совместимость, так что нужно проигнорировать название в их табличке и взять аналог из предыдущей версии чтобы получилось вот так `33 => IncomingExistExternalIdError`.

ПР будет очень полезным, ошибка серьезная. Нужно учесть обратную совместимость и подобрать для всех изменений (пока не смотрел если другие изменения вообще, нужно выделить вермя и проверить) вариант из старой версии, как я сделал в примере выше.
