### ISSUE TITLE
Указать company_email в обязательных параметрах инициализации

### ISSUE THREAD

**Issue by Magicdream** [sputnik8/atol-rb#3]
Необходимо обновить wiki и указать company_email, как обязательный параметр инициализации приложения.
```
Atol.config.tap do |config|
  ...
  config.company_email   = "you@email.com"
end
```
Спасибо

**Comment by GeorgeGorbanev** [comment]
Спасибо за замечание, добавил в список переменные и дописал возможные значения https://github.com/sputnik8/atol-rb/pull/4

**Comment by GeorgeGorbanev** [comment]
Смерджили
